name: Create Release

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not main
  pull_request:
    types: [closed]
    branches:
      - main  # Only trigger on pull requests to the main branch

jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Fetch at least the last 2 commits

    - name: Set up date and time
      id: date
      run: |
        echo "DATE_TAG=$(date -u +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Check for changes in Mupdate.lua
      id: check_changes
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q 'Mupdate.lua'; then
          echo "CHANGED=true" >> $GITHUB_ENV
        else
          echo "CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Create Release
      if: github.repository_owner == 'gesslar' && env.CHANGED == 'true'
      uses: ncipollo/release-action@v1
      with:
        artifacts: "LICENSE,Mupdate.lua,README.md"
        allowUpdates: true
        bodyFile: "./README.md"
        tag: ${{ env.DATE_TAG }}
        name: Release ${{ env.DATE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine if it's a merged PR or direct commit
      id: check_pr
      run: |
        if [ "${{ github.event_name }}" == "push" ]; then
          echo "IS_MERGED=false" >> $GITHUB_ENV
        elif [ "${{ github.event.pull_request.merged }}" == "true" ]; then
          echo "IS_MERGED=true" >> $GITHUB_ENV
        else
          echo "IS_MERGED=false" >> $GITHUB_ENV
        fi
      shell: bash
