name: Create Release

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not main

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up date and time
      id: date
      run: |
        echo "DATE_TAG=$(date -u +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.DATE_TAG }}
        release_name: Release ${{ env.DATE_TAG }}
        body: "Automated release created on ${{ env.DATE_TAG }}"
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: LICENSE
        asset_name: LICENSE
        asset_content_type: text/plain

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Mupdate.lua
        asset_name: Mupdate.lua
        asset_content_type: text/plain

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: README.md
        asset_name: README.md
        asset_content_type: text/markdown
